### ISSUE TITLE
Installing Libraries: Permission Error

### ISSUE THREAD

**Issue by lfunderburk** [callysto/training-manual#1]
I am currently collaborating as a Callysto creator and have been following the training documentation. When I try to install libraries I get an error message and I am not allowed to finish installing. I would be grateful for any feedback. Here is the procedure I am following:

1. Login to sfu.syzygy.ca with appropriate credentials
2. Open a new notebook
3. Install desired libraries, for example

`!pip install pygame`

or

`!pip install pyplot`

4. Installation begins but it is not finished. Here is output

Collecting pygame
  Downloading https://files.pythonhosted.org/packages/e4/c7/f57009a23c8f0520031be7042aa78407d88843876b2a504d4990e753fb70/pygame-1.9.3-cp36-cp36m-manylinux1_x86_64.whl (9.4MB)
    100% |████████████████████████████████| 9.4MB 93kB/s  eta 0:00:01
Installing collected packages: pygame
Exception:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/conda/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/conda/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/conda/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/conda/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/opt/conda/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/opt/conda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/conda/lib/python3.6/site-packages/pygame'

**Comment by lfunderburk** [comment]
Was pointed out to a solution. 

Run pip install with option

`pip install --user`

Thank you !!
